const PRODUCTS_ACTIONS_TYPES = {
    START_OFFER: "START_OFFER",
    GET_OFFERS_SUCCESS: 'GET_OFFERS_SUCCESS',
    GET_OFFERS_FAILED: 'GET_OFFERS_FAILED',

    START_FEATURED_PRODUCTS: "START_FEATURED_PRODUCTS",
    GET_FEATURED_PRODUCTS_SUCCESS: 'GET_FEATURED_PRODUCTS_SUCCESS',
    GET_FEATURED_PRODUCTS_FAILED: 'GET_FEATURED_PRODUCTS_FAILED',

    START_TRENDING_PRODUCTS: "START_TRENDING_PRODUCTS",
    GET_TRENDING_PRODUCTS_SUCCESS: 'GET_TRENDING_PRODUCTS_SUCCESS',
    GET_TRENDING_PRODUCTS_FAILED: 'GET_TRENDING_PRODUCTS_FAILED',

    START_FEATURED_CATEGORIES: "START_FEATURED_CATEGORIES",
    GET_FEATURED_CATEGORIES_SUCCESS: 'GET_FEATURED_CATEGORIES_SUCCESS',
    GET_FEATURED_CATEGORIES_FAILED: 'GET_FEATURED_CATEGORIES_FAILED',

};

export default PRODUCTS_ACTIONS_TYPES;
