const PRODUCTS_ACTIONS_TYPES = {
    GET_OFFERS_SUCCESS: 'GET_OFFERS_SUCCESS',
    GET_OFFERS_FAILED: 'GET_OFFERS_FAILED',

    GET_FEATURED_PRODUCTS_SUCCESS: 'GET_FEATURED_PRODUCTS_SUCCESS',
    GET_FEATURED_PRODUCTS_FAILED: 'GET_FEATURED_PRODUCTS_FAILED',

    GET_TRENDING_PRODUCTS_SUCCESS: 'GET_TRENDING_PRODUCTS_SUCCESS',
    GET_TRENDING_PRODUCTS_FAILED: 'GET_TRENDING_PRODUCTS_FAILED',

    RELOADING: 'RELOADING'

};

export default PRODUCTS_ACTIONS_TYPES;
