export const PRODUCTTYPE = {
    OFFERPRODUCT_SUCCSS: 'OFFERPRODUCT_SUCCSS',
    OFFERPRODUCT_FAILD: 'OFFERPRODUCT_FAILD',
    TRENDINGPRODUCT_SUCCSS: 'TRENDINGPRODUCT_SUCCSS',
    TRENDINGPRODUCT_FAILD: 'TRENDINGPRODUCT_FAILD'
}
